### ISSUE TITLE
"target_plots must be an int, list, tuple, or 'all'." in add_data.py

### ISSUE THREAD

**Issue by nibudd** [dwhit15/multiplot2d#12]
What is causing this?

**Comment by dwhit15** [comment]
Does this only happen in add_data.py? Not the other examples?

**Comment by nibudd** [comment]
Only in add_data.py, yes

**Comment by dwhit15** [comment]
For Python 2 and 3 or just 3?

**Comment by nibudd** [comment]
just py3. issuing pull request for dev-py3 now

**Comment by dwhit15** [comment]
Cool I will investigate today or tomorrow. Most likely one of the if statements in _target_plots_exist() does not work the same in 3 as in 2.

**Comment by nibudd** [comment]
fixed in direct push to dev branch.
Python3 doesn't create lists or tuples from ranges, but generators. The add_data.py example was using range(2) as a list or tuple and then multiplot2d was ensuring it was a list or tuple, which it wasn't. The example now casts the range to a list, which allows it to work for both Python 2 and 3.

**Comment by dwhit15** [comment]
That makes a lot of sense; actually just read about this particular Python 2 vs 3 issue like yesterday.
